Repository planetlabs/planet-client-python, pull requests merged in 2021-12, with the labels that each got.

#344 Added to .gitignore
  .gitignore
Labels: ux

#346 Added support for 8-band imagery bundles in v1
  planet/scripts/item_asset_types.py
Labels: enhancement, new feature

#350 Handle mix of single target items and source lists when printing the listing of mosaics in feeds
  CHANGES.txt
  planet/scripts/v1.py
  setup.py
  tests/fixtures/feeds.json
Labels: bug
