Repository planetlabs/planet-client-python, pull requests merged in 2022-11, with the labels that each got.

#762 Updated Data API example, resolving rate limiting issue
  examples/download_multiple_assets.py
Labels: bug

#780 Updated Harmonization tool to match the openAPI spec
  docs/cli/cli-orders.md
  planet/order_request.py
  tests/unit/test_order_request.py
Labels: new feature, orders api

#776 Enable permalinks for section headers
  mkdocs.yml
Labels: enhancement, documentation
