Repository planetlabs/planet-client-python, pull requests merged in 2022-10, with the labels that each got.

#680 Get supported bundles for a given item_type
  planet/cli/orders.py
  planet/order_request.py
  planet/specs.py
  tests/integration/test_orders_cli.py
  tests/unit/test_data_callbacks.py
  tests/unit/test_specs.py
Labels: ux

#713 Validated item type with specs module
  planet/cli/data.py
  tests/integration/test_orders_cli.py
  tests/unit/test_data_callbacks.py
Labels: enhancement

#717 Updated User Guide's and CLI Reference's links
  README.md
Labels: bug, documentation

#722 Downloading multiple assets in parallel example
  examples/download_multiple_assets.py
Labels: documentation

#728 Bug fixes, asset type, and item type updates to create and download orders example
  examples/orders_create_and_download_multiple_orders.py
Labels: bug, fixup

#737 Remove accidental request-1.json commit
  request-1.json
Labels: admin
