Repository planetlabs/planet-client-python, pull requests merged in 2022-09, with the labels that each got.

#687 bugfix: Using f-string on subscription url
  planet/clients/subscriptions.py
Labels: bug

#685 Enable redirect following and avoid treating 302s as errors
  planet/http.py
  tests/integration/test_orders_api.py
Labels: bug

#695 Human readable invalid item_type report
  planet/cli/data.py
  tests/unit/test_data_item_type.py
Labels: enhancement

#700 Updated stac docstring.
  planet/cli/orders.py
Labels: feedback
