Repository planetlabs/planet-client-python, pull requests merged in 2023-07, with the labels that each got.

#973 Replace single- with double-quote for docstrings, as per PEP-257
  noxfile.py
  planet/auth.py
  planet/cli/auth.py
  planet/cli/data.py
  planet/cli/orders.py
  planet/cli/subscriptions.py
  planet/clients/orders.py
  planet/constants.py
  planet/exceptions.py
  planet/http.py
  planet/order_request.py
  planet/specs.py
  planet/subscription_request.py
  tests/conftest.py
  tests/integration/test_auth_cli.py
  tests/integration/test_orders_api.py
  tests/integration/test_orders_cli.py
  tests/unit/test_auth.py
  tests/unit/test_order_request.py
  tests/unit/test_specs.py
  tests/unit/test_subscription_request.py
Labels: bug, documentation

#975 Ignore type errors involving click decorators
  planet/cli/auth.py
  planet/cli/cli.py
  planet/cli/data.py
  planet/cli/options.py
  planet/cli/orders.py
  planet/cli/subscriptions.py
Labels: bug

#971 Add a clip_to_source kwarg to subscript_request.build_request
  CHANGES.txt
  planet/subscription_request.py
  setup.cfg
  setup.py
  tests/integration/test_data_api.py
  tests/unit/test_subscription_request.py
Labels: enhancement, subscriptions api

#976 Add a planetary_variable_source subscription helper
  CHANGES.txt
  planet/subscription_request.py
  tests/unit/test_subscription_request.py
Labels: enhancement, subscriptions api

#977 Add support for catalog source publishing stages
  CHANGES.txt
  docs/stylesheets/extra.css
  planet/subscription_request.py
  tests/unit/test_subscription_request.py
Labels: enhancement, subscriptions api

#978 Add support for Subscriptions time range types
  CHANGES.txt
  planet/subscription_request.py
  tests/unit/test_subscription_request.py
Labels: enhancement, subscriptions api

#988 request-pv and request --clip-to-source
  CHANGES.txt
  planet/cli/subscriptions.py
  planet/subscription_request.py
  tests/integration/test_subscriptions_cli.py
Labels: enhancement, subscriptions api

#989 Updated order delivery config for zipped orders
  .gitignore
  planet/order_request.py
  tests/unit/test_order_request.py
Labels: bug, orders api

#990 Add archive options to planet-orders-request
  CHANGES.txt
  planet/cli/orders.py
  planet/cli/subscriptions.py
  planet/order_request.py
  tests/unit/test_order_request.py
Labels: enhancement, orders api

#992 Add CLI support for subs publishing stages and time range types
  CHANGES.txt
  planet/cli/subscriptions.py
  tests/integration/test_subscriptions_cli.py
Labels: enhancement, subscriptions api

#991 Document new CLI features of 2.1.0
  docs/cli/cli-orders.md
  docs/cli/cli-subscriptions.md
Labels: documentation

#998 Import Literal from typing_extensions
  .github/workflows/test.yml
  CHANGES.txt
  noxfile.py
  planet/clients/subscriptions.py
  planet/subscription_request.py
Labels: bug

#999 updated cli docs
  docs/cli/cli-guide.md
Labels: bug, documentation

#1008 Don't ensurepip: no longer needed
  CHANGES.txt
  noxfile.py
Labels: bug, tests, sdk-2023.7
